### ISSUE TITLE
hi~ about gpu and others

### ISSUE THREAD

**Issue by jun0wanan** [TheShadow29/VidSitu#10]
hi,

 Thank you for your excellent work ! Approximately how many GPUs are needed for the experiment of the whole data set？How big is the data set including features~~(●'◡'●)

Best,
jun

**Comment by TheShadow29** [comment]
The verb prediction task involves training the video backbone which would require 20 hours on 4 gpus. 

The semantic role prediction and event role prediction can be done on 1 gpu in around 6 hours.

**Comment by jun0wanan** [comment]
> The verb prediction task involves training the video backbone which would require 20 hours on 4 gpus.
> 
> The semantic role prediction and event role prediction can be done on 1 gpu in around 6 hours.

wow～ What about feat size？
