### ISSUE TITLE
Regarding the SlowFast NL verb prediction run 

### ISSUE THREAD

**Issue by fanyix** [TheShadow29/VidSitu#18]
Hi, thanks for the awesome dataset! 
I was checking your SlowFast+NL verb prediction run (log: https://drive.google.com/file/d/18bKlwJi4oiNH6J2MQaGYHylKkok8QOKE/view) and saw the config on non-local part looks like this:  `"NONLOCAL": {"GROUP": [[1, 1], [1, 1], [1, 1], [1, 1]], "INSTANTIATION": "dot_product", "LOCATION": [[[], []], [[], []], [[], []], [[], []]], "POOL": [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]}`

With `"LOCATION": [[[], []], [[], []], [[], []], [[], []]]`, it looks like you're not using non-local block? Or am I misunderstanding something here? 

Also, where can I find the pretrained model `"./weights/SLOWFAST_CU_8x8_R50.pkl"`? Thanks!

**Comment by TheShadow29** [comment]
@fanyix Ouch, seems like you are right. It is then a mistake in the paper then. I will look into fixing it. It should be just SlowFast. 

The model used is from "Kinetics/c2/SLOWFAST_8x8_R50" from https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md

**Comment by fanyix** [comment]
Got it, thanks for the clarification. Will close the the issue.
