### ISSUE TITLE
Modified Data Prep Instructions

### ISSUE THREAD

**Issue by dfan** [TheShadow29/VidSitu#19]
The instructions for installation at [[DATA_PRE_.md](https://github.com/TheShadow29/VidSitu/blob/main/data/DATA_PREP.md) should be amended to mention `pip install yt-dlp`. 
This is due to the change in #17  to use yt-dlp in the download script.

**Comment by TheShadow29** [comment]
Good catch! I updated it. Feel free to re-open the issue if you face any issues!
