### ISSUE TITLE
What is the version of yt-dlp?

### ISSUE THREAD

**Issue by a670531899** [TheShadow29/VidSitu#21]
What is the version of yt-dlp?

When I use the dwn_yt.py scripts to download videos, it says "Unrecognized option '-cookies'.".

Is it a version problem?

Or can I just use youtube-dl to download videos by myself?

**Comment by TheShadow29** [comment]
@a670531899 could you let me know what command you used?

you need to use "--cookies=/path/to/cookiesfile" 

yt-dlp (as far as I know) is better maintained youtube-dl. Using latest version is recommended.

**Comment by a670531899** [comment]
I used this cmd
`python prep_data/dwn_yt.py --task_type='dwn_vids' --max_processes=30 --cookies_file=cookies.txt`
And I get this error:
_Unrecognized option '-cookies'.
Error splitting the argument list: Option not found_

**Comment by TheShadow29** [comment]
@a670531899 I recall now, I think with yt-dlp you don't need to use cookies (they mention this in their readme). cookies was for an earlier version which relied on youtube-dl

Let me know if it works out

**Comment by a670531899** [comment]
@TheShadow29  Thanks for your reply! And I have fixed this problem.

However, I have a doubt when I want to predict the arguments with the predicted verbs. 
**Why does the argument generation process need the annotation?**

Specifically, it is the code in mdl_sf_base.py:
`inp_prep = self.prepare_prev_toks_inp(inp)`
`inp["src_tokens"] = inp_prep["dst_toks"][..., :1]`
`inp["src_lengths"] = inp_prep["dst_lens"]`
`inp_ids = inp_prep["dst_toks"][..., :1]`
There you use the dst_toks which is loaded from the annotation file.

That's really confused me, looking for your reply.

**Comment by TheShadow29** [comment]
@a670531899 Great! 

I take up until the first token (which is the given). In our task, you are given the verb, and you need to predict the semantic roles. 

`inp_ids = inp_prep["dst_toks"][..., :1]` just takes the first verb token as the input ids. You can consider these to be the prefixes for the decoder.

Does that answer your question?

**Comment by a670531899** [comment]
@TheShadow29  Thank you! That's very helpful.

**Comment by TheShadow29** [comment]
@a670531899 feel free to create a new issue if you have any questions!
