### ISSUE TITLE
Why testset annotations for SRL and EventRelation task released?

### ISSUE THREAD

**Issue by Alexstrasza98** [TheShadow29/VidSitu#22]
To my knowledge, isn't VidSitu still an open competition? Why the test set annotations released? If not, why annotations for verb prediction missing. Thanks!

**Comment by TheShadow29** [comment]
@Alexstrasza98 The three tasks have disjoint test sets. 

So for verb task, there are no annotations.

For SRL, the verb annotation is provided. 

For event relation, verb + SRL annotation is provided. 

Let me know if that answers your question.

**Comment by Alexstrasza98** [comment]
Sorry for late reply! Yes, it makes sense. Thanks for clarification.
