### ISSUE TITLE
The evaluation code is inconsistent with the README file description

### ISSUE THREAD

**Issue by wkw1259** [TheShadow29/VidSitu#23]
Thanks for providing the great dataset!

When I reproduced your results, I found that there is no code/evl_fns.py file, and there is no code folder. I'm guessing you mean the vidsitu_code/evl_fns.py file. However, there are some parameters (such as PRED_FILE TASK_TYPE SPLIT_FILE_PATH VINFO_FILE_PATH VSITU_ANN_FILE_PATH SPLIT_TYPE) that I don't know how to set them, and I can't find them in the log file you provided. 

Could you please provide an example of running the evalutation file? Thanks a lot!

**Comment by TheShadow29** [comment]
@wkw1259 pred_file is the prediction file that you want to use, task_type is vb/vb_arg/evrel, the remaining three are the split_file_path, vinfo_file_path and vsitu_ann_file_path which you find when you download the dataset under three different folders (make sure to use the validation ones when running locally), split_type is 'valid' when running locally.

Let me know if it works

**Comment by wkw1259** [comment]
It works! thanks! Sorry for wasting some of your time answering this simple question. I'wll close the issue.
