### ISSUE TITLE
Issue in downloading video and extracting frames

### ISSUE THREAD

**Issue by cws7777** [TheShadow29/VidSitu#3]
Hi, thank you for your awesome work! :)

I've followed `INSTALL.md` step by step, and got stuck #2(ii) and #3 in `DATA_PREP.md` which is "Download the videos" step.
After typing the command `python prep_data/dwn_yt.py --task_type='dwn_vids'`, the process goes through but it gives a message as below:
![image](https://user-images.githubusercontent.com/12144129/115332084-1b68f700-a1d2-11eb-8248-cc8b000dfc13.png)

I thought those messages might not be a matter, but it gives nothing when I typed `python prep_data/dwn_yt.py --task_type='extract_frames'`. So I realized those messages might be the matter

Is there any `FEATURE_ZIP_LINK`?  that I can download? or Did I miss some steps?

Thanks! :)

**Comment by TheShadow29** [comment]
@cws7777 Thanks for your interest. 

It seems like the videos are not downloaded. Can you check if the target video directory exist?

Your ffmpeg version may need upgrade. If you are using conda environment, can you try `conda install ffmpeg`

I have updated the feature link now (I forgot to push the previous changes).

Let me know if the issue still persists.

**Comment by cws7777** [comment]
@TheShadow29 Thanks for prompt reply! Do you mean the directory called `vsitu_video_frames_dir` and `vsitu_video_trimmed_dir`? If you do, then there are both directories in data directory. :)
Oh I see, I just upgraded the `ffmpeg`, but still appeared same messages.

I might use the alternative way that you mentioned on #4 in `DATA_PREP.md`

**Comment by TheShadow29** [comment]
@cws7777 Can you check if any video is downloaded to the `vsitu_video_trimmed_dir`?

Also, which conda environment are you using?

**Comment by cws7777** [comment]
@TheShadow29 There is nothing on `vsitu_video_trimmed_dir`. (Actually, I just ran the command and it appears same message. So I stopped with `ctrl+c`)

I'm using just conda (not miniconda) and the environment that you explained in the INSTALL.md (which is `conda env create -f vsitu_pyt_env.yml --prefix $MINICONDA_ROOT/envs/vsitu_pyt`)

May this cause the error..?? :'(

**Comment by TheShadow29** [comment]
My guess is that `youtube-dl` needs to be updated with `pip install youtube-dl --upgrade`. 

I have re-uploaded the conda environment (with fixed youtube-dl version). You could either try the above line or try a fresh install. It seems to be working on my machine. 

If the issue persists, I will try to replicate the issue on another machine as well.

**Comment by cws7777** [comment]
Thank you so much for helping me out! :)
I upgraded and it shows `Requirement already up-to-date: youtube-dl in ~~~(2021.4.17)`
Fixed version that you put in `.yml` file is `2021.4.7`, so I might try to upgrade(maybe downgrade(?)) again with the fixed version.
I'll try and let you know soon! :)

P.S. I just did alternative way. (Downloaded the `vsitu_vidfeats_drive.zip` and unzip the file in the `$root/data/vsitu_vid_feats`)

Thanks once again! :D

**Comment by cws7777** [comment]
I will try the fresh install as well and let you know! :D

Thanks once again!

**Comment by cws7777** [comment]
Oh crap... I was implementing in the main env which is `vsitu_pyt`, not in `vsitu_data_env`... :'(
My mistake...!Sorry for the confusion.
The code goes through well and there are videos(`.mp4 files`) in the `vsitu_video_trimmed_dir` directory.

Thank you once again for helping me out!

**Comment by TheShadow29** [comment]
Awesome! Feel free to create a new issue if any problem arises!
