### ISSUE TITLE
Problem on the downloading videos

### ISSUE THREAD

**Issue by liujiaheng** [TheShadow29/VidSitu#5]
I run the code
`python prep_data/dwn_yt.py --task_type='dwn_vids'`,
and I often following the warnings.
![image](https://user-images.githubusercontent.com/27964642/116494112-bd739800-a8d2-11eb-87d5-1d861e45bc68.png)
![image](https://user-images.githubusercontent.com/27964642/116494158-d419ef00-a8d2-11eb-9821-bf4adf3c7473.png)

In the end, I have obtained 17344 videos (*.mp4) in the "data/vsitu_video_trimmed_dir" folder. Many videos are left out, because my ip has been blocked (I guess).
Could you upload the videos on google drive or other public cloud services?

Thanks.

**Comment by TheShadow29** [comment]
Could you share the log file generated in prep_data folder?

**Comment by liujiaheng** [comment]
![image](https://user-images.githubusercontent.com/27964642/116521068-17da1c00-a906-11eb-942b-a0207e71b1dc.png)

![image](https://user-images.githubusercontent.com/27964642/116521477-9b940880-a906-11eb-8961-95cd2f3a8685.png)

The 'problematic_vidsegs.txt' is generated in 'prep_data' folder. There are 12044 lines. 
Besides, there are 17735 mp4 videos in 'data/vsitu_video_trimmed_dir' folder.

**Comment by TheShadow29** [comment]
@liujiaheng This is indeed strange. My guess is as good as yours that there is some IP restriction. Let me get back (by today/tomorrow) on how to best share this.
