### ISSUE TITLE
Not able to download the full dataset

### ISSUE THREAD

**Issue by rui1996** [TheShadow29/VidSitu#7]
Hi,

I strictly followed every step in the prep_data.md but was only able to download 15746 of the 29220 total videos. 
I guess most of them encountered https request denied and 403 forbiddening.

Is there any way to deal with this?

**Comment by rui1996** [comment]
My issue is very similar to this [issue](https://github.com/TheShadow29/VidSitu/issues/5) and we both encounter the ip forbidden problem, would you mind sharing a full video version online in case the frames are too large?

**Comment by TheShadow29** [comment]
Hi @rui1996 Thanks for your interest

Are you able to view the "problematic" videos via any web-browser?

**Comment by rui1996** [comment]
Thank you for your response!
I do try to view a few "problematic" videos and find it is also access denied in chrome browser, but I guess it may not be the case for all missing videos? Since I can only download 15k of 29k videos....

**Comment by sidney1994** [comment]
Hi @TheShadow29, I have the same problem.  I can only download 17287 of the 29220 total videos

**Comment by TheShadow29** [comment]
@sidney1994 can you confirm you are not able to view the videos from your chrome? 

I just retried downloading the videos yesterday and could download ~27k of them, with the remaining having age restriction. I have fixed it locally but yet to push the changes (the solution is to use cookies with youtube-dl).

**Comment by rui1996** [comment]
I opened a new GCP instance for downloading, and now able to get 28 of the 29k videos. It is so weird!
